.github/workflows/lint.yml
README.md

This is a cleaner python flake8 lint which uses actionsv4 and doesn't throw an error about actions.yml not existing.
Once this PR is approved, and runs, I'll make another one to remove the lints.yml that errors.

trying better python lint action

---

.flake8
Developers.md
pyproject.toml
requirements.txt

I didn't have the pre-commit check for black and ruff installed. 
This adds developer docs, flake8 config and ruff config to ignore line too long.

precommit lint check and Developer doc

---

swarms/prompts/agent_system_prompts.py

Improvement in ouput formats in agent_system_prompts.py

---

tests/structs/test_swarmnetwork.py

_____________________________ ERROR collecting tests/structs/test_swarmnetwork.py _____________________________
ImportError while importing test module '/home/v/vswarms/tests/structs/test_swarmnetwork.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
tests/structs/test_swarmnetwork.py:5: in <module>
from swarms.structs.swarm_net import SwarmNet
E   ImportError: cannot import name 'SwarmNet' from 'swarms.structs.swarm_net' (/home/v/.local/lib/python3.10/site-packages/swarms/structs/swarm_net.py)

[BUGF] [SwarmNet] [test_swarmnetwork]

---

swarms/models/huggingface.py

Description:
Remove breaking .to(device) 
Issue:
```python
ValueError: `.to` is not supported for `4-bit` or `8-bit` bitsandbytes models. Please use the model as it is, since the model has already been set to the correct devices and casted to the correct `dtype`.
```
----
📚 Documentation preview 📚: https://swarms--450.org.readthedocs.build/en/450/

quantized models don't have .to

---

pyproject.toml

pyyaml required, not yaml
----
📚 Documentation preview 📚: https://swarms--449.org.readthedocs.build/en/449/

Fixed install from source

---

docs/swarms/install/docker_setup.md

The sample docker file installed netcat which is not available as a package under that name. It's not a needed dependency, so I removed it.
----
📚 Documentation preview 📚: https://swarms--535.org.readthedocs.build/en/535/

Update docker_setup.md remove netcat

---

docs/swarms_platform/fetch_prompts.md
docs/swarms_platform/prompts_api.md

Updated the swarms-platform markdown files for `fetching_prompts.md` file with latest query and fetch prompts by id implementations with code examples and `prompts_api.md` file with `edit-prompt` code examples and usage.
----
📚 Documentation preview 📚: https://swarms--547.org.readthedocs.build/en/547/

feat: update prompts docs

---

examples/rearrange_swarm_with_langchain_v1_astream_events/example.py
examples/swarms/rearrange/example.py
swarms/structs/agent.py
swarms/structs/rearrange.py

Description: Adding NON-BREAKING/BACKWARDS-COMPATIBLE support for LangChain's v1 astream events to the AgentRearrange & Agent classes. PLUS this PR include an example of how to use it.
Issue: Would like to stream the tokens of each agent in a swarm for enhanced UI/UX for a Web Application I am building on top of Swarms
Dependencies: No additional work needed other than merging
Maintainer: @kyegomez 
Twitter handle: @cmd_labs on X.com
Leaving below for reference...
See contribution guidelines for …

adding NON-BREAKING/BACKWARDS-COMPATIBLE support for LangChain's v1 astream event

---

swarms/structs/concurrent_workflow.py

The ConcurrentWorkflow class was raising an AttributeError because the tasks attribute was not properly initialized in the class constructor. When the run() method attempted to access self.tasks, it failed because the attribute didn't exist. This caused workflows to fail when trying to execute tasks, particularly affecting use cases where tasks were added incrementally or when running multiple tasks in sequence.
- The tasks attribute was missing from the class's __init__ method
- The code assumed the existence of self.tasks but never properly initialized it
- This caused the workflow to fail immediately upon attempting to access the tasks list
The fix implements the following changes:
- Added proper initialization of self.tasks = [] in the __init__ method
- Modified the task handling …

Fix AttributeError in ConcurrentWorkflow by Properly Initializing Tasks List

---

docs/swarms/concept/framework_architecture.md

Just a simple typo fix.
----
📚 Documentation preview 📚: https://swarms--620.org.readthedocs.build/en/620/

Fixed typo in docs

---

.github/workflows/python-package.yml

- Description: remove 3.9 from python packaging action
- Issue: the minimum python version supported is now, 3.10, this removes testing on the older python
- Dependencies: none
- Tag maintainer: 
**I will need to clean up quite a bit before I get a clean lint, and test.**
1. a test for the integration, preferably unit tests that do not rely on network access,
2. an example notebook …

remove 3.9 from python packaging action

---

swarms/tools/base_tool.py

before it was just returning the last schema now it returns the entire schema appended 
bug fix : https://github.com/kyegomez/swarms/issues/661
----
📚 Documentation preview 📚: https://swarms--665.org.readthedocs.build/en/665/

return appended entire schema

---

swarms/structs/agent.py

the bug is technically you have to give the name of the file and not just the extension
bug fixed : https://github.com/kyegomez/swarms/issues/656
----
📚 Documentation preview 📚: https://swarms--664.org.readthedocs.build/en/664/

handle artifact bug fix

---

.env.example

Issue:
- The issue I am encountering arises from having multiple entries for OPENAI_API_KEY in your .env.example file. When the environment variables are loaded, the latter entry overwrites the former, leading to potential confusion or misconfiguration.
Solution:
- Remove Duplicate Entries: Ensure that each environment variable is defined only once in your .env.example file. This practice prevents unintended overwrites and maintains clarity.
----
📚 Documentation preview 📚: https://swarms--712.org.readthedocs.build/en/712/

remove duplicate OPENAI_API_KEY

---

swarms/structs/multi_agent_orchestrator.py

In Python >= 3.11 UTC is implemented in the datetime function, but in Python 3.10 it is implemented in the timezone function

fix datetime utc compatibility

---

README.md

I've added Mermaid diagrams to visualize the architecture and flow of key components in the README.md file. The diagrams include:
Basic Swarm Architecture
Communication Patterns
Agent Class Structure
RAG Integration Flow
Sequential Workflow
Agent Rearrange Architecture
Graph Swarm Structure
Mixture of Agents Flow
Spreadsheet Swarm Process
Forest Swarm Architecture
Swarm Router Flow
Group Chat Flow
----
📚 Documentation preview 📚: https://swarms--748.org.readthedocs.build/en/748/

add graphs

---

examples/onboard/agents.yaml
examples/onboard/onboard-basic.py
swarms/agents/create_agents_from_yaml.py
swarms/cli/main.py

Overall UX was bit confusing for me 
Now it logs better 
Also Added onboard example
----
📚 Documentation preview 📚: https://swarms--745.org.readthedocs.build/en/745/

Imporve the UX of CLI and Add onboard examples

---

swarms/structs/groupchat.py

- Description: 
This pull request includes an important change to the `reliability_check` method in the `swarms/structs/groupchat.py` file. The change ensures that at least two agents are required for a group chat, improving the reliability check process.
* [`swarms/structs/groupchat.py`](diffhunk://#diff-2f2fa7afc32857b502279c00b02f31a06ea184ed4c2637151f242dcb93767298L251-R252): Modified the `reliability_check` method to raise a `ValueError` if fewer than two agents are provided, ensuring that group chats have a minimum of two agents.
----
📚 Documentation preview 📚: https://swarms--776.org.readthedocs.build/en/776/

fix: groupchat needs more than 2 agents

---

requirements.txt

Update requirements.txt: transformers version <4.49.0, 
LogitsWarper deprecated in  transformers 4.49.0
used in tools/logits_processor.py: 
"""
class OutputNumbersTokens(transformers.LogitsWarper):
"""
This PR addresses an issue caused by the recent release of the transformers library version 4.49.0, where the LogitsWarper class has been deprecated. The tools/logits_processor.py file in the swarms codebase currently references this deprecated class, which may lead to runtime errors.
----
📚 Documentation preview 📚: https://swarms--781.org.readthedocs.build/en/781/

Update transformers requirement from >=4.39.0,<5.0.0 to >=4.39.0,<4.49.0; LogitsWarper deprecated in transformers version 4.49.0

---

swarms/structs/Talk_Hier.py

This PR introduces the `TalkHier` framework, a novel hierarchical multi-agent system designed for structured content generation and refinement.  `TalkHier` leverages a team of specialized agents, each with a distinct role, to collaboratively produce high-quality content through iterative communication and evaluation.
**Key Features:**
*   **Hierarchical Multi-Agent System:**  `TalkHier` employs a hierarchical structure with agents specializing in different aspects of content creation:
*   **Supervisor:** Orchestrates the entire process, analyzes tasks, selects evaluation criteria, and guides revision.
*   **Generator:** Creates initial content based on instructions.
*   **Evaluator (Multiple):** Critically assesses content quality against dynamically generated criteria.
*   **Revisor:** …

feat: Implement TalkHier framework for hierarchical multi-agent content generation

---

docs/swarms/concept/why.md
pyproject.toml

This PR fixes a critical syntax error in the Mermaid diagram describing context window limitations in the documentation. The original diagram was producing a "Syntax error in textmermaid version 11.6.0" due to incorrect subgraph syntax, preventing proper rendering of the visualization.
- Fixed subgraph syntax by properly implementing `subgraph` and `end` tags
- Corrected the node structure to ensure proper rendering in Mermaid 11.6.0
- Maintained the original conceptual flow showing how large documents get truncated before processing
None
@kyegomez 
----
📚 Documentation preview 📚: https://swarms--823.org.readthedocs.build/en/823/

fix(docs): Resolve Mermaid Syntax Error in Context Window Diagram

---

pyproject.toml

- **Description:**  
This PR resolves runtime import errors by adding `mcp` and `fastmcp` as dependencies in `pyproject.toml`. These packages are essential for enabling MCP-based integrations inside `swarms/tools/mcp_integration.py` and `swarms/tools/mcp_client.py`.
- **Issue Fixed:**  
Fixes `ModuleNotFoundError: No module named 'mcp'` and `fastmcp` when running `example.py`.  
Even though `example.py` does not explicitly import these modules, they are required internally via the `Agent` class and related toolchains.
- **Dependencies Added:**  
- `mcp = "*"`  
- `fastmcp = "*"`
- **Maintainer Tag:** @kyegomez  
- **Twitter handle (optional):** [@the_complex_one](https://x.com/the_complex_one)
These additions ensure editable installs with `pip install -e .` include all necessary …

fix: resolve ModuleNotFoundError by adding mcp and fastmcp to pyproject.toml

---

docs/swarms/install/quickstart.md

This PR updates the quickstart documentation examples by replacing explicit LLM initialization with the streamlined `model_name` parameter approach. Key changes:
- Removed `swarm_models` imports (`Anthropic`, `OpenAIChat`)
- Replaced `llm=Anthropic()` with `model_name="claude-3-sonnet-20240229"`
- Replaced `llm=OpenAIChat(...)` with `model_name="gpt-4o-mini"`
- Eliminated explicit API key handling with `os.getenv()`
- Updated examples for SequentialWorkflow, AgentRearrange, and SpreadSheetSwarm
These changes maintain identical functionality while simplifying the code examples for new users.
N/A 
No new dependencies 
@kyegomez 
----
📚 Documentation preview 📚: https://swarms--826.org.readthedocs.build/en/826/

fix: update quickstart examples to use model_name parameter

---

examples/communication_examples/pulsar_conversation.py

This PR adds an example under pulsar_conversation.py demonstrating how to use the `PulsarConversation` class to store and retrieve chat history in Apache Pulsar.  
The example shows how to configure a Pulsar-backed conversation store, create an agent that uses this persistent memory, run a sample query, and print both the agent’s response and the stored messages.
**Issue:**  
N/A
**Dependencies:**  
- Requires a running Apache Pulsar broker (default: `pulsar://localhost:6650`)
- Requires the `pulsar-client` Python package (`pip install pulsar-client`)
**Tag maintainer:**  
@kyegomez
---
**Steps to test:**
1. **Start an Apache Pulsar broker** (if not already running):
```bash
docker run -it -p 6650:6650 -p 8080:8080 apachepulsar/pulsar:latest bin/pulsar standalone
```
2. …

Add Apache Pulsar conversation example

---

examples/communication_examples/sqlite_conversation.py

This PR adds an example demonstrating how to persist agent dialogue using the `SQLiteConversation` class in Swarms.
**Issue:**  
N/A
**Dependencies:**  
N/A
**Tag maintainer:**  
@kyegomez

Add SQLite conversation example

---

swarms/structs/agent_rag_handler.py

This PR updates the `field_validator` usage in agent_rag_handler.py to be compatible with Pydantic v2.11.4, which is the version pinned in our requirements.txt. The fix ensures that our RAG functionality works correctly with the current dependencies.
**Technical Details:**
- Changed `@field_validator("relevance_keywords", pre=True)` to `@field_validator("relevance_keywords", mode="before")`
- The `pre=True` parameter was valid in Pydantic v1.x but was replaced with `mode="before"` in Pydantic v2.x
- This fixes the `TypeError: field_validator() got an unexpected keyword argument 'pre'` error that was occurring during test execution
**Impact:**
This change ensures that all code dependent on the `RAGConfig` class in agent_rag_handler.py works correctly, including tests and …

[fix][compatibility][deps][bugfix][bounty-eligible] Fix field_validator syntax for Pydantic v2

---

swarms/utils/vllm_wrapper.py

This PR optimizes the thread pool worker count calculation in the vLLM wrapper utility. The change ensures:
1. At least one worker thread is always created (preventing potential errors)
2. CPU resources are efficiently utilized without over-subscription (using 95% of cores)
**Technical Details:**
- In vllm_wrapper.py, updated the batch worker calculation formula to:
```python
max(1, int((os.cpu_count() or 1) * 0.95))
```
- Previously, the calculation could potentially result in zero workers in specific environments
- The 0.95 multiplier prevents thread contention while maximizing parallel processing
**Impact:**
- Prevents errors when running in environments where thread calculation might result in zero
- Improves resource utilization by optimizing thread count based on …

[perf][fix][utils][bounty-eligible] Update worker count in ThreadPoolExecutor

---

swarms/agents/reasoning_agents.py

- Description: 
Refactored the agent selection mechanism in the ReasoningAgentRouter class by implementing a factory pattern with dictionary mapping to replace the lengthy if-elif chain structure.
The original code used a long chain of if-elif statements for agent type selection, which becomes increasingly difficult to maintain as the number of supported agent types grows. This refactoring aims to improve:
Efficiency - Dictionary lookups have O(1) time complexity, making them more efficient than long if-elif chains
Maintainability - Each agent type's creation logic is now encapsulated in dedicated methods
Extensibility - Adding new agent types only requires adding a new mapping to the dictionary, without modifying the …

replace-conditionals-with-factory-pattern

---

swarms/structs/interactive_groupchat.py

After fix, run the example video:https://www.loom.com/share/7dd7772c9b8847e69c02c1a1b1597a8c?sid=67b8a668-6211-4893-8c25-f7bf92f71540
Problem
In the current implementation, when users select random_speaker, the system doesn't select a single agent to respond as expected. Instead, it returns responses from all agents, with their order randomly shuffled. This behavior contradicts the intended functionality of random_speaker, which should randomly select exactly one agent to respond to the user's question.
Solution
This PR implements proper random speaker functionality by:
Add a dedicated _process_random_speaker method to handle the case where the user selects random_speaker
Modifying the run method to detect when random_speaker is selected and route execution to our new specialized handler …

fix random_speaker issues 

---

docs/mkdocs.yml

- Description: changed the connection method for "Agent on MCP" on full documentation (as has been routed the wrong way within the files)
----
📚 Documentation preview 📚: https://swarms--1069.org.readthedocs.build/en/1069/

Fixed mcp_ds.md routing for documentation

---

swarms/structs/agent.py

Description: Fix AttributeError in Agent.to_dict() method when autosave=True
Issue: https://github.com/kyegomez/swarms/issues/1125
Root Cause:
The to_dict() method at line 2410 in swarms/structs/agent.py permanently removed the llm attribute from the agent instance:
```python
def to_dict(self) -> Dict[str, Any]:
self.__dict__.pop("llm", None)
return {
attr_name: self._serialize_attr(attr_name, attr_value)
for attr_name, attr_value in self.__dict__.items()
}
```
When autosave=True, the agent initialization calls log_agent_data(self.to_dict()) at line 673, which triggers to_dict() and removes the llm attribute. Later, when the code checks if self.llm is None at line 678, it fails because the attribute no longer exists.
Fix:
Modified to_dict() to create a copy of __dict__ instead of mutating …

[BUGF-ATTR][Fixed Autosave Attr-error]
