- swarms/models/__init__.py
<!-- Thank you for contributing to Swarms!
- Description: pipe stderr to a log file, 
- Issue: improve the way text is presented in terminal to be less noisy (easeier to read) and create a progress bar or similar visualization for while agents are "thinking",
- Dependencies: none
- Tag maintainer: n/a
- Twitter handle: n/a
1. a test for the integration, preferably unit tests that do not rely on network access,
2. an example notebook showing its use.
Maintainer responsibilities:
- General / Misc / if you don't know who to tag: kye@apac.ai
- DataLoaders / VectorStores / Retrievers: kye@apac.ai
- Models / Prompts: kye@apac.ai
- Memory: kye@apac.ai
- Agents / Tools / Toolkits: kye@apac.ai
- Tracing / Callbacks: …
> pipe stderr to log file

- .env.example
- apps/discord.py
- docs/applications/discord.md
- playground/apps/discord_example.py
- tests/apps/discord.py
----
:books: Documentation preview :books:: https://swarms--66.org.readthedocs.build/en/66/
> Discord bot framework

- .github/labeler.yml
- .github/workflows/welcome.yml
<!-- Thank you for contributing to Swarms!
Added a base labeler.yml so the Labeler github action can get a bit farther.
> added labeler.yml

- swarms/models/zephyr.py
<!-- Thank you for contributing to Swarms!
1. a test for the integration, preferably unit tests that do not rely on network access,
2. an example notebook showing its use.
Maintainer responsibilities:
- General / Misc / if you don't know who to tag: kye@apac.ai
- DataLoaders / VectorStores / Retrievers: kye@apac.ai
- Models / Prompts: kye@apac.ai …
> fix: typo bfloat16

- README.md
- swarms_example.ipynb
In order to make trying out swarms easier, I have created a one button deploy  to colab notebook and README update.
tummycom …
> Example colab notebook

- swarms/models/openai_models.py
> Update openai_models.py (new model, increased context and reasoning)

- playground/demos/idea_2_img/idea2img.py
- swarms/models/stable_diffusion.py
- swarms/prompts/idea2img.py
> idea2img file and prompt, plus stablediffusion class fix

- requirements.txt
> Update requirements.txt typo

- swarms/prompts/agent_system_prompts.py
> update agent_system_prompts for reliability and quality outputs

- swarms/models/multion.py
- tests/models/test_multion.py
> multion implementation and tests

- tests/models/test_LLM.py
> test_LLM langchain openai import issue #310

- tests/structs/test_autoscaler.py
> test_autoscaler fix patch #315

- .github/workflows/testing.yml
python-version: 3.10
If you're adding a new integration, please …
> Bumping python version for testing.yml

- .github/workflows/testing.yml
> Update testing.yml - python version in quotes

- requirements.txt
> Reqs20240108 - bump datasets, remove pin for huggingface-hub add toml

- scripts/auto_tests_docs/auto_tests_functions.py
> [CLEA] remove duplicate import

- docs/swarms/utils/pdf_to_text.md
- pyproject.toml
- requirements.txt
- swarms/loaders/pdf_loader.py
- swarms/utils/pdf_to_text.py
- tests/utils/test_pdf_to_text.py
PyPDF2 is [deprecated](https://pypi.org/project/PyPDF2/) and development is moving back to the original pypdf.
----
📚 Documentation preview 📚: https://swarms--386.org.readthedocs.build/en/386/
> Update PDF library from PyPDF2 to pypdf

- README.md
- Description: Improved readability and clarity of the README file., 
- Issue: N/A,
- Dependencies: N/A,
- Tag maintainer: @kyegomez,
- Twitter handle: @cyber_holics
1. a test for the integration, preferably unit tests that do not rely on network access,
2. an example notebook showing its use.
Maintainer responsibilities:
- General / Misc / if you don't know who to tag: kye@apac.ai
- …
> improve swarmd README.md

- .github/workflows/docs.yml
The initial 3 --- are a yaml lint suggestion, but incompatible with gh actions. …
> Update docs.yml remove leading ---

- README.md
Remove  type annotation
Error: SyntaxError: positional argument follows keyword argument
----
📚 Documentation preview 📚: https://swarms--529.org.readthedocs.build/en/529/
> Update README.md typo in agent + ltm example

- docs/swarms_platform/agents_api.md
- docs/swarms_platform/fetch_agents.md
Documentation on agents api
----
📚 Documentation preview 📚: https://swarms--551.org.readthedocs.build/en/551/
> feat: add docs for agents api

- README.md
https://github.com/kyegomez/swarms/issues/533
update Swarms Platform link to https://swarms.world …
> [fix] update Swarms Platform link to https://swarms.world

- playground/agents/monitoring/agent_ops.py
- playground/agents/monitoring/agent_ops_tools.py
- swarms/structs/agent.py
- swarms/structs/base_swarm.py
- swarms/structs/rearrange.py
- swarms/tools/tool_parse_exec.py
The problem was the function:
def __eq__(self, other):
return self.__dict__ == other.__dict__
in BaseSwarm in base_swarm.py
@kyegomez not sure if it was useful...
This function was added on https://github.com/kyegomez/swarms/commit/68605261f02636e09982ad0377cbc64b8293d4a4
----
📚 Documentation preview 📚: https://swarms--557.org.readthedocs.build/en/557/
> AGENTOPS FIX

- docs/mkdocs.yml
- docs/swarms/structs/taskqueue_swarm.md
Added a simple md doc for Taskqueue-swarms
----
📚 Documentation preview 📚: https://swarms--608.org.readthedocs.build/en/608/
> Add TaskQueueSwarm documentation

- docs/swarms_cloud/architecture.md
The words are duplicate in the document. Use this change to tidy them. …
> docs: remove duplicated words

- README.md
> Update README.md with working discord link

- docs/applications/business-analyst-agent.md
- docs/corporate/data_room.md
> chore: fix typos

- examples/vllm_example.py
- requirements.txt
- swarms/utils/vllm_wrapper.py
This PR adds vLLM integration to the Swarms project, providing a high-performance inference wrapper that follows the same interface as LiteLLM. The implementation includes:
- VLLMWrapper class with configurable parameters
- Support for system prompts and batched inference
- Error handling and logging
- Example usage in examples/vllm_example.py
Fixes #724 (Using vLLM-hosted models)
Added vllm>=0.2.0 to requirements.txt
The implementation includes:
- Type hints for better code maintainability
- Comprehensive docstrings
- Error handling with logging
- Example code demonstrating usage
@kyegomez (General / Misc)
@the_complex_one
- The VLLMWrapper follows the same interface as LiteLLM for consistency
- Includes automatic installation of vLLM if not present
- Supports both single and batched …
> Add vLLM support with wrapper and example

- README.md
- docs/swarms/install/quickstart.md
- example.py
- examples/async_agent.py
- examples/example_async_vs_multithread.py
This PR simplifies Swarms code examples and documentation by removing the dependency on the `swarm_models` package. It refactors examples to use the `model_name` parameter directly in Agent initialization, which provides a cleaner API experience for users. Provider prefixes (e.g., "openai/gpt-4o-mini") have been added to model names for better clarity and consistency.
This change reduces cognitive overhead for new users by eliminating the need to understand and manage external model initializations, while maintaining full functionality.
N/A - General code improvement
No new dependencies - this PR actually removes a dependency requirement
@kyegomez - This affects swarms.models and general usage examples
----
📚 Documentation preview 📚: …
> fix: Remove swarm_models dependency and simplify Agent initialization

- docs/swarms/concept/philosophy.md
This PR updates the Mermaid workflow diagram in the philosophy documentation to use modern syntax. Key changes:
- Changed `graph TD` to `flowchart TD` for better compatibility with current Mermaid versions
- Added proper quotes around node text and connection labels
- Improved formatting of diagram elements for better rendering
- Updated the collaborative workflow example in section 4.4
These changes ensure the diagram renders correctly in GitHub and other Mermaid-compatible viewers while maintaining the same visual workflow representation.
N/A 
No new dependencies 
@kyegomez 
----
📚 Documentation preview 📚: https://swarms--827.org.readthedocs.build/en/827/
> fix: update mermaid workflow diagram syntax

- docs/swarms/install/quickstart.md
This PR updates the documentation for creating agents from YAML to use the simplified API. Key changes:
- Removed nested `model` configuration section in YAML
- Replaced explicit API key handling with direct `model_name` parameter
- Added support for `swarm_architecture` configuration in YAML
- Simplified the main script by removing unnecessary imports and setup code
- Changed example to use Claude models instead of OpenAI models
- Updated return_type from "tasks" to "run_swarm"
- Removed environment variable loading and explicit model creation
The updated documentation provides a cleaner, more straightforward approach for users to create and configure agents from YAML files.
N/A 
No new dependencies 
@kyegomez 
----
📚 Documentation …
> fix: simplify YAML-based agent creation

- docs/swarms/structs/agent.md
This PR simplifies the Financial Agent example by:
- Updating the import path to use `swarms.structs.agent` instead of direct `swarms` import
- Removing the OpenAIChat model instance creation and dependency
- Removing the need for the OPENAI_API_KEY environment variable
- Replacing the `llm` parameter with the direct `model_name` parameter
- Updating to use "gpt-4o-mini" as the model
N/A
None
@kyegomez 
----
📚 Documentation preview 📚: https://swarms--831.org.readthedocs.build/en/831/
> Update agent.md documentation

- docs/swarms/memory/diy_memory.md
- docs/swarms/structs/agent.md
This PR updates the Agent initialization pattern by:
- Changing import path from `swarms` to `swarms.structs.agent`
- Replacing the `llm` parameter with direct `model_name` parameter
- Adding response capture with print statement
N/A
None
@kyegomez 
----
📚 Documentation preview 📚: https://swarms--832.org.readthedocs.build/en/832/
> Update diy memory md

- docs/swarms/structs/multi_agent_collaboration_examples.md
- Description: Updated the GraphWorkflow implementation to directly configure agents with GPT-4o-mini instead of using OpenAIChat LLM models. Restructured imports and improved agent configuration with proper naming and state management.
- Issue: N/A
- Dependencies: None
- Tag maintainer: @kyegomez 
- Twitter handle: [the_complex_one](https://x.com/the_complex_one)
> Fix/Update GraphWorkflow Implementation with GPT-4o-mini Agents

- swarms/structs/deep_research_swarm.py
This pull request refines the functionality of the `DeepResearchSwarm` class in `swarms/structs/deep_research_swarm.py` to improve error handling, enhance search and reasoning workflows, and introduce new features for displaying and exporting results. The changes focus on improving robustness, usability, and output formatting.
* Added checks for the presence of the `EXA_API_KEY` environment variable, returning an error message if it is missing.
* Enhanced error handling in the `step` method to gracefully handle issues during query processing and final summary generation, including detailed error messages logged using `console.print`. [[1]](diffhunk://#diff-8c174c25426440241d7d37622d7698b3ac026b6522b1298c682a46589a5d9939R420-R459) …
> Fixed #865 DeepResearchSwarm

- docs/swarms/agents/reasoning_duo.md
- examples/models/reasoning_duo_batched.py
This PR adds a new example script demonstrating how to initialize the `ReasoningDuo` class with two lightweight models and process tasks in a batch. The example is placed under models and is referenced in the ReasoningDuo documentation for easy discovery by users seeking runnable code.
**Key Changes:**
- Added reasoning_duo_batched.py to show batched task processing with ReasoningDuo.
- Updated reasoning_duo.md to link to the new example.
**Issue:**  
N/A
**Dependencies:**  
N/A
**Tag maintainer:**  
@kyegomez
----
📚 Documentation preview 📚: https://swarms--902.org.readthedocs.build/en/902/
> [docs][example][reasoningduo][bounty-eligible] Add example for batched task initialization

- docs/examples/index.md
- examples/structs/graph_workflow_basic.py
This PR adds a new example script demonstrating how to build and execute a minimal graph workflow using Swarms. The script creates two agents, connects them to a single task node, and runs the workflow. The example is also referenced in the documentation index for easy discovery.
**Key Changes:**
- Added graph_workflow_basic.py to showcase a basic graph workflow with two agents and one task.
- Updated index.md to include the new example under the "Core Architectures" section.
**Issue:**  
N/A (new example)
**Dependencies:**  
None 
**Tag maintainer:**  
@kyegomez
----
📚 Documentation preview 📚: https://swarms--905.org.readthedocs.build/en/905/
> [docs][example][workflow]Create example script for graph workflow

- stream_example.py
- swarms/structs/agent.py
- swarms/utils/formatter.py
- swarms/utils/litellm_wrapper.py
This pull request introduces **real-time streaming capabilities** #921  to the Swarms framework, enabling users to receive and display Agent responses incrementally with immediate visual feedback. The implementation features a beautiful Rich terminal UI with live panels, blinking cursors, and automatic text wrapping, bringing Swarms agents into the modern era of real-time AI interactions.
- **Real-time token streaming** directly from LiteLLM completion API
- **Beautiful Rich terminal UI** with live panels and visual indicators  
- **Automatic text wrapping** and responsive formatting
- **Blinking cursor animation** during streaming with completion indicator (✅)
- **Seamless tool integration** with smart streaming management
- **Enable streaming in `Agent`:** Added `streaming_on` parameter …
> feat: Implement real-time streaming with Rich UI for Agent responses

- bug_report.md
- swarms/structs/agent.py
- Description: This PR addresses three critical bugs in the `swarms/structs/agent.py` file:
1.  **Error Handling:** Fixed a critical issue in `_handle_run_error` where exceptions raised in a daemon thread would not propagate to the main thread, leading to silent failures. The fix ensures direct error handling for proper exception propagation.
2.  **Typo Fixes:** Corrected two typos (`reponse` to `response`) in the `add_response_filter` and `apply_response_filters` methods, which previously caused `AttributeError` and prevented response filtering from functioning correctly.
3.  **Document Ingestion Logic:** Resolved a logic error in `ingest_docs` where only the last document was processed, leading to data loss when ingesting multiple documents. The fix …
> Fix three bugs in the codebase

- examples/multi_agent/concurrent_examples/streaming_concurrent_workflow.py
- scripts/setup.sh
- swarms/structs/agent.py
- swarms/structs/concurrent_workflow.py
This pull request introduces a streaming callback mechanism to enable real-time token streaming and dashboard integration for agents in the `swarms` module. The changes include modifications to the `Agent` class to support the callback and updates to the `ConcurrentWorkflow` class to integrate the streaming functionality with the dashboard.
* Added a `streaming_callback` parameter to the `_run`, `run`, and `call_llm` methods in `swarms/structs/agent.py`. This parameter allows passing a callback function to handle streaming tokens in real-time. [[1]](diffhunk://#diff-76dda3e4659d2af1a87d31ef5b71580793ac95d3a00e2a0aeffb288e15f5a44fR999) [[2]](diffhunk://#diff-76dda3e4659d2af1a87d31ef5b71580793ac95d3a00e2a0aeffb288e15f5a44fR2476) [[3]](diffhunk://#diff-76dda3e4659d2af1a87d31ef5b71580793ac95d3 …
> fix streaming in ConcurrentWorkflow !

- examples/stagehand/1_stagehand_wrapper_agent.py
- examples/stagehand/2_stagehand_tools_agent.py
- examples/stagehand/3_stagehand_mcp_agent.py
- examples/stagehand/4_stagehand_multi_agent_workflow.py
- examples/stagehand/README.md
- examples/stagehand/requirements.txt
- tests/stagehand/test_stagehand_integration.py
- tests/stagehand/test_stagehand_simple.py
---
Description
This PR adds comprehensive integration examples for Stagehand, an AI-powered browser automation framework, with the Swarms multi-agent framework. The
integration provides three different approaches for incorporating browser automation capabilities into Swarms agents:
1. Wrapper Agent: A complete Swarms-compatible agent that wraps Stagehand's browser automation
2. Tools Integration: Individual Stagehand methods exposed as Swarms tools (navigate, act, extract, observe, screenshot)
3. MCP Server Integration: Connection to Stagehand's Model Context Protocol server for standardized tool access
The integration enables natural language browser automation within multi-agent workflows, supporting use cases like e-commerce monitoring, competitive
analysis, automated testing, and web …
> add stagehand example

- examples/utils/misc/conversation_test.py
- examples/utils/misc/conversation_test_truncate.py
- swarms/structs/conversation.py
test video :https://www.loom.com/share/5604ff8bcf96492db6ab61e877512bfe?sid=2caeb218-7768-4243-abee-3add4c5822bf
close #984 
This PR fixes the token truncation bug reported in Issue #984, where the truncate_memory_with_tokenizer function used character-based rather than token-based truncation methods, resulting in incorrect results.
Changes:
Re-implemented the truncate_memory_with_tokenizer function with a smarter truncation strategy
Added a new _binary_search_truncate helper function that uses binary search to determine the precise truncation point
Added optimization for truncation at sentence boundaries, improving readability of truncated text
Enhanced handling of non-string content types
Provided comprehensive test suite validating various truncation scenarios
Key Improvements:
The …
> Fix: Optimize Conversation History Token Truncation Algorithm

- examples/demos/crypto/dao_swarm.py
- Description: The "auto_save" and "dashboard" parameters were preventing execution of the file, so removed and added with a "max_loop" to make more efficient. 
- Dependencies: no changes.
----
📚 Documentation preview 📚: https://swarms--1046.org.readthedocs.build/en/1046/
> updated dao_swarm to current version

- docs/mkdocs.yml
- docs/swarms/utils/fallback_models.md
- swarms/structs/agent.py
This PR implements a comprehensive fallback model system for the Swarms Agent class, enabling automatic switching to alternative models when the primary model fails. This enhancement significantly improves agent reliability and ensures continuous operation even when individual models encounter issues such as rate limits, API errors, or temporary unavailability.
Addresses the need for robust model fallback mechanisms in production environments where model reliability is critical. This implementation provides a universal solution that works across all Agent instances without breaking existing functionality.
- No new external dependencies required
- Maintains full backward compatibility with existing Agent implementations
- Leverages existing LiteLLM infrastructure
@kyegomez …
> [FEAT-AGENT][Added fallback models function to agent, if primary model were to fail]

- swarms/structs/heavy_swarm.py
Optimized all agent prompts in HeavySwarm for enhanced technical precision, systematic analysis capabilities, and comprehensive outcome calculation while maintaining cost efficiency. The changes transform verbose, generic prompts into concise, methodology-driven instructions that enable models to perform rigorous statistical analysis and systematic decision-making.
https://github.com/kyegomez/swarms/issues/1090
**Before:**
```python
RESEARCH_AGENT_PROMPT = """
You are an expert Research Agent with exceptional capabilities in:
CORE EXPERTISE:
- Comprehensive information gathering and synthesis
- Primary and secondary research methodologies
- Data collection, validation, and verification
- Market research and competitive analysis
- Academic and industry report analysis
- Statistical data …
```
> [PROMPTS][Fixed & improved `Heavy_swarm` prompts to be more concise, to the point, and debloated.]

- pyproject.toml
- swarms/structs/__init__.py
- swarms/structs/multi_agent_exec.py
Implemented cross-platform async performance optimization for Swarms by adding support for both uvloop (Linux/macOS) and winloop (Windows) event loops. This ensures optimal async performance across all platforms while maintaining backward compatibility.
https://github.com/kyegomez/swarms/issues/1113
- uvloop: For Linux and macOS platforms
- winloop: For Windows platforms
- Platform-specific conditional installation via pyproject.toml markers
**Before:**
```toml
uvloop = {version = "*", markers = "sys_platform != 'win32'"}
```
**After:**
```toml
uvloop = {version = "*", markers = "sys_platform == 'linux' or sys_platform == 'darwin'"}
winloop = {version = "*", markers = "sys_platform == 'win32'"}
```
**Why this works:** Platform markers ensure only compatible event loop libraries are …
> [IMPROVEMENT-UVLOOP][Added `uvloop`/as/`winloop` compatibility for windows users]

- swarms/structs/auto_swarm_builder.py
- tests/structs/test_auto_swarm_builder_fix.py
- Description: a description of the change,
1. a test for the integration, preferably unit tests …
> fix Attempting to unpack Pydantic BaseModel directly with ** operator

- docs/examples/aop_medical.md
- docs/mkdocs.yml
- examples/aop_examples/medical_aop/client.py
- examples/aop_examples/medical_aop/server.py
Added a Medical AOP (Agent Orchestration Protocol) example demonstrating real-world deployment of medical agents as MCP tools. This implementation showcases:
- AOP server setup with 5 specialized medical agents (Chief Medical Officer, Virologist, Internist, Medical Coder, Diagnostic Synthesizer)
- Structured JSON schemas with validation, priority levels, and confidence scoring
- Discovery tools for dynamic agent collaboration and search
- Real tool execution with keyless API integration (disease.sh for epidemiology data)
- Complete documentation with Mermaid architecture diagrams
- Cursor MCP integration examples
https://github.com/kyegomez/swarms/issues/1112
- mcp-server-fastmcp
- requests (for keyless API integration)
- loguru (for structured logging)
@kyegomez …
> [EXAMPLE-AOP][Created AOP example with Medical Agents]
